base_url = "https://gptparv.github.io"
title = "Today I Learned"
description = "Developer journal with learnings from day to day activities and knowledge base"
theme = "abridge"

default_language = "en"
compile_sass = true
minify_html = false
build_search_index = true
generate_feeds = true
taxonomies = [{ name = "tags", feed = true }]

[search]
index_format = "elasticlunr_json"
include_title = true
include_description = true
include_content = true

[markdown]
highlight_code = true
highlight_theme = "css"
bottom_footnotes = true
render_emoji = false
external_links_target_blank = true
external_links_no_follow = false
external_links_no_referrer = false
smart_punctuation = false

[extra]
###############################################################################
### Layout & Format
### position: top, bottom, both, false(hidden)
### size: s150, s140, s130, s120, s110, s95, s90, s85, s80, s75, s70, false(full size)
### divider:    " "        "&middot;"        "&bull;"
###############################################################################

menu = [
    { url = "posts", name = "Posts", slash = true, blank = false, size = "s110" },
    { url = "tags", name = "Tags", slash = true, blank = false, size = "s110" },
]
menu_footer = [
    { url = "about", name = "About", slash = true, blank = false, size = "s90" },
    { url = "contact", name = "Contact", slash = true, blank = false, size = "s90" },
    { url = "privacy", name = "Privacy", slash = true, blank = false, size = "s90" },
    { url = "sitemap.xml", name = "Sitemap", slash = false, blank = true, size = "s90" },
]

toc = true
recent = true
recent_items = 15
series = true
series_items = 9
Series_parts = "$NUMBER_OF_PARTS part Series"

meta_index = { position = "bottom", size = "s90", author = false, readtime = false, readstring = "min", date = true, updated = false, categories_tags = true, divider = "" }
meta_post = { position = "top", size = "s95", author = true, readtime = false, readstring = "min read", date = true, updated = true, categories_tags = true, divider = "" }

hide_section_dates = false
hide_page_nextprev_titles = false
title_size_index = "s85"
footer_size = "s80"
footer_credit = true

textlogo = '<font color="#f90">T</font>oday I Learned'

sitedesc = false
headhr = true
foothr = true

###############################################################################
### meta/seo/analytic tags
### To disable title_addition but keep built in page additions eg, Posts page: "Posts | Abridge" set title_addition to an empty string
### To always set the page title exactly eg "Abridge" then comment out title_addition or set to false (not recommend, bad for SEO)
###############################################################################

title_separator = "|"                                 # Separator between title and title_addition, set as |, -, _, etc
title_addition = "Knowledge base by learning"         # a default value for title addition (for SEO aim for 50-70 characters including the title and separator 'Abridge | title_addition')
author = "Parv Gupta"                                 # Put Your Name here
keywords = "DevOps, Platform Engineering, SRE, Linux"
banner = "banner.png"                                 # Used as default image for OpenGraph/Twitter if page specific image is undefined.
# twitter_meta = "your-user-name"                             # for SEO: twitter:site and twitter:creator
# google = "Your Google Site verification code."
# bing = "Your Bing Site verification code."
seo = true # enable or disable seo-related meta tags: opengraph, facebook, twitter
#dev = false # development mode, if true then robots.txt should prevent search indexing.

###############################################################################
### Footer social links; these are used in macros/social.html
###   https://github.com/Jieiku/abridge/blob/master/templates/macros/social.html
###############################################################################

feed = true # this adds the RSS feed icon in the footer.
# mail = "name@example.com"
# mastodon = "https://mastodon.example.com/@username"
# element = "matrix.example.com"
#buymeacoffee = "your-user-name"
# kofi = "your-user-name"
#discord = "https://discord.com/invite/my-server" # https://discord.com/invite/my-server  *or*  https://discord.com/servers/my-server-id
#twitter = "your-user-name"
#facebook = "your-user-name"
#linkedin = "your-user-name"
#gitlab = "your-user-name"
# github = "your-user-name"
#codeberg = "your-user-name" # Everything after https://codeberg.org/   eg: username  *or*  username/repository
#github_sponsor = "your-user-name"
#bitbucket = "your-user-name"
#python = "your-user-name"
#docker = "your-user-name"
#stack = "your-user-name"
# instagram = "your-user-name"
#pixelfed = "https://pixelfed.example.com/" # Heaviest icon, off by default
#pinterest = "your-user-name"
# twitch = "your-user-name"
# youtube = "channel/your-channel-id"
#peertube = "https://peertube.example.com/@username"
#researchgate = "your-profile-id"
#telegram = "your-user-name"


###############################################################################
### Resource Files
### You can load extra css files if you need to, just separate by comma:
### stylesheets = [ "abridge.css", "extra.css" ]
### search_library, library to use. valid values:
###   false, "elasticlunr", "elasticlunrjava", "pagefind", "tinysearch", "offline"
###     elasticlunr - elasticlunr using the elasticlunr_json index format
###     elasticlunrjava - elasticlunr using the elasticlunr_javascript index format
###     pagefind - pagefind using the fuse_json index format
###     tinysearch - tinysearch using the fuse_json index format
###     offline - elasticlunr using the elasticlunr_javascript index format with content paths relative to the location on disk.
###       (offline: implies uglyurls=true and integrity=false, node script will pass base_url argument as the path on disk.)
###
###       The PWA feature is another way to build an offline site, so there are now two
###       different ways to build an offline site with Abridge.
###############################################################################

uglyurls = false # if set to true then links are generated with the full path. eg https://abridge.netlify.app/index.html
integrity = true # increases site security, should normally be true. (setting to false is useful during js development)
js_bundle = true # multiple javascript files combined into a single file (setting to false is useful during js development)

js_copycode = true           # The copy button on code blocks that allows you to copy them to the clipboard.
js_email_encode = true       # obfuscates email address in footer
js_prestyle = true           # used to preload: FontAwesome, Katex, external Google Fonts
js_switcher = true           # The button that allows manually changing between light/dark mode.
js_switcher_default = "dark" # default nojs switcher mode: dark, light (make sure to also set $switcherDefault in abridge.scss)

search_library = "elasticlunr"
stylesheets = ["abridge.css"]

webmanifest = "manifest.min.json" # Required for PWAs


###############################################################################
### PWA (Progressive Web Application)
### By default Abridge has pwa_NORM_TTL and pwa_LONG_TTL set to 0, this essential turns the PWA cache strategy into network first.
###  Abridge uses cachebust hashing on js and css files, so anytime a page cache is updated, these resources would also get updated if changed.
###  Media files rarely change, especially font files, so it is a good idea cache indefinitely.
###  For pwa_TTL_EXEMPT indefinitely cached resources, you can force a new cache by incrementing the pwa_VER (cache version number).
### If you would like to try a cache first strategy then set a value higher than 0 for pwa_NORM_TTL and pwa_LONG_TTL.
###  The options below other than pwa=true, only come into play when the npm/node script is ran.
###############################################################################

pwa = true         # true to load the service worker
pwa_VER = '3.12.1' # Service Worker cache version. (increment if you need to force a new cache)

### 3600=1hour, 28800=8hours, 86400=1day, 604800=1week, 1209600=2weeks
pwa_NORM_TTL = 0 #  86400 is reasonable. html, json, xml, anything else undefined
pwa_LONG_TTL = 0 # 604800 is reasonable.

### list of files that overrides TTL_LONG/TTL_EXEMPT to be a NORM TTL.
pwa_TTL_NORM = '"sw.min.js", "sw_load.min.js"'

### TTL_LONG file extensions will be cached for the LONG_TTL duration.
pwa_TTL_LONG = '"jpg", "jpeg", "png", "gif", "webp", "avif", "ico", "svg", "xsl", "txt"'

### TTL_EXEMPT file extensions will be cached indefinitely unless sw_load version is incremented, which would invalidate any existing cache. (and a new cache would be started)
pwa_TTL_EXEMPT = '"js", "css", "otf", "eot", "ttf", "woff", "woff2", "mp4", "webm", "mp3", "ogg"'

### If set to true then the entire site is cached. (useful for making an entire site usable while offline)
pwa_cache_all = true

### List of Files for the PWA to initially Cache, used if pwa_cache_all = false
pwa_BASE_CACHE_FILES = "'/js/theme.min.js','/js/theme_light.min.js','/abridge.css','/js/abridge.min.js','/','/404.html','/offline/','/manifest.min.json'"

pwa_IGNORE_FILES = ["_headers", "sw.min.js", "sw.js"]
#pwa_IGNORE_FILES = ["_headers","sw.min.js","sw.js","android-chrome-192x192.png","android-chrome-512x512.png","apple-touch-icon.png","favicon-16x16.png","favicon-32x32.png","favicon.ico","m48.png","m72.png","m96.png","m128.png","m192.png","m384.png","m512.png","m1024.png","mstile-150x150.png"]

###############################################################################
### Favicons, comment out a line to disable loading some or all of these if needed.
###############################################################################

favicon_theme_color = "#333333"
favicon_ms_color = "#333333"
favicon_mask = "safari-pinned-tab.svg" # safari-pinned-tab.svg
favicon_mask_color = "#ff9900"
favicon_svg = "favicon.svg"            # favicon.svg
favicon180 = "apple-touch-icon.png"    # apple-touch-icon.png
favicon32 = "favicon-32x32.png"        # favicon-32x32.png
favicon16 = "favicon-16x16.png"        # favicon-16x16.png


###############################################################################
### Commenting System for visitors to leave comments on pages.
###   hyvor talk
###############################################################################

#comments.hyvor = "9366" # hyvor website id, comment out to disable.
#comments.hyvorcolor = "os" # set the color property for hyvor


###############################################################################
### Icons
### Loading the entire fontawesome icon collection will negatively impact your sites performance.
### For a lightweight solution consider adding only the icons that you need.
### you can load individual scss based svg icons by including them in the _extra.scss file
### https://github.com/Jieiku/abridge/blob/master/COPY-TO-ROOT-SASS/_extra.scss
###############################################################################

### To disable any of these icons set them to "false" (will default to unicode icons instead)
#icon_search = "svgs svgm search" # Search button in search box.
#icon_adjust = "svgs adjust" # Theme Switcher button in top menu. (add class svgh to change colors on hover)
#icon_first = "svgs svgh angll" # Pagination First Page.
#icon_prev = "svgs svgh angl" # Pagination Previous Page.
#icon_next = "svgs svgh angr" # Pagination Next Page.
#icon_last = "svgs svgh angrr" # Pagination Last Page.
#icon_top = "svgs svgh angu" # Back to Top Button.

#icon_read = "svgs fa-solid fa-glasses" # displayed in metadata on index and below title on page.
#icon_date = "svgs fa-solid fa-calendar" # displayed in metadata on index and below title on page.
#icon_info = "svgs fa-solid fa-circle-info" # displayed in metadata on index and below title on page for categories/tags
#icon_author = "svgs fa-solid fa-pen-fancy" # displayed in metadata on index and below title on page.

### Uncomment below line to load fontawesome, eg: <i class="fa-solid fa-heart"></i>
#fontawesome = "https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.1.1/css/all.min.css"
#icon_read = "svgs fa-solid fa-glasses" # displayed in metadata on index and below title on page.
#icon_date = "svgs fa-solid fa-calendar" # displayed in metadata on index and below title on page.
#icon_info = "svgs fa-solid fa-circle-info" # displayed in metadata on index and below title on page for categories/tags
#icon_author = "svgs fa-solid fa-pen-fancy" # displayed in metadata on index and below title on page.


###############################################################################
### Security Settings
### Security Headers should preferably be set by your webserver (Nginx, Apache)
###   https://observatory.mozilla.org  https://csp-evaluator.withgoogle.com/
### If you are unable to load your security headers with your webserver, this will load a couple of them as meta tags.
### There are many other security related headers most of which can only be set by the webserver method.
### If you happen to use Netlify, you can define all the headers in your netlify.toml file:
###   https://github.com/Jieiku/abridge/blob/master/netlify.toml
### UnComment any of these lines to enable their meta tags.
###############################################################################

#security_header_referrer = "strict-origin-when-cross-origin"

#security_header_csp = "default-src 'none'; object-src 'none'; base-uri 'self'; manifest-src 'self'; connect-src 'self'; form-action 'self'; script-src 'self'; img-src 'self' data: cdn.cloudflare.com; frame-src 'self' www.youtube-nocookie.com player.vimeo.com; media-src 'self' data: cdn.cloudflare.com www.youtube-nocookie.com player.vimeo.com; font-src 'self' cdn.cloudflare.com cdn.jsdelivr.net fonts.gstatic.com; style-src 'self' cdn.cloudflare.com cdn.jsdelivr.net fonts.googleapis.com;"


###############################################################################
### FONTS - Abridge by default uses the System Font Stack
###   https://css-tricks.com/snippets/css/system-font-stack/
### However if you need you can load a specific font below,
###   make sure to have the relevant woff2 fonts in your static/fonts folder
### I measured the least Cumulative Layout Shift with: Roboto, Lato, Arimo
###############################################################################

### For externally loaded Fonts, make sure to include the FULL url including the https prefix:

#fonts = [ {url = "https://fonts.googleapis.com/css?family=Roboto:400,700,italic|Roboto+Mono:400,italic"} ]

### Local fonts are defined in the css, https://github.com/Jieiku/abridge/tree/master/COPY-TO-ROOT-SASS/fonts/_Arimo.scss
### To load a local font resource, look at the bottom of this file: https://github.com/Jieiku/abridge/blob/master/COPY-TO-ROOT-SASS/abridge.scss

### After loading them in the CSS, You can also define them below and it will add the preload tag to the head.
### preloading fonts will eliminate Content Layout Shift, but will hurt with page load time. (not recommended)

#fonts = [
#    {url = "fonts/Roboto-Mono.woff2"},
#    {url = "fonts/Roboto-Mono-Italic.woff2"},
#    {url = "fonts/Roboto.woff2"},
#    {url = "fonts/Roboto-Italic.woff2"},
#    {url = "fonts/Roboto-Bold.woff2"},
#]
